ALTER TABLE questions ADD COLUMN times_used INTEGER NOT NULL DEFAULT 0;
ALTER TABLE questions ADD COLUMN times_correct INTEGER NOT NULL DEFAULT 0;
ALTER TABLE questions ADD COLUMN times_wrong INTEGER NOT NULL DEFAULT 0;
